WITH RANKED AS (
    SELECT 
        DEPARTMENTID,
        SALARY,
        NAME,
        DENSE_RANK() OVER(PARTITION BY DEPARTMENTID ORDER BY SALARY DESC) AS NUM
    FROM EMPLOYEE
)
SELECT 
    D.NAME AS Department,
    R.NAME AS Employee,
    R.SALARY
FROM RANKED AS R
JOIN DEPARTMENT AS D
ON R.DEPARTMENTID = D.ID
WHERE NUM = 1