WITH LOCATION_CONDITION_MATCHED AS (
    SELECT 
        CONCAT(lat, lon) AS LOCATION,
        COUNT(PID) AS CNT
    FROM INSURANCE
    GROUP BY CONCAT(lat, lon)
    HAVING CNT = 1
),
TIV_CONDITION_MATCHED AS (
    SELECT TIV_2015 
    FROM INSURANCE
    GROUP BY TIV_2015
    HAVING COUNT(*) > 1
)

SELECT
    ROUND(SUM(P.TIV_2016),2) AS tiv_2016
FROM INSURANCE AS P
JOIN LOCATION_CONDITION_MATCHED AS L
ON CONCAT(P.lat, P.lon) = L.LOCATION
JOIN TIV_CONDITION_MATCHED AS T
ON T.TIV_2015 = P.TIV_2015

