WITH MATERIAL AS (
SELECT
    'R' AS TYPE,
    requester_id AS ID,
    COUNT(DISTINCT ACCEPTER_ID) AS NUM
FROM RequestAccepted
GROUP BY ID
UNION ALL
SELECT 
    'A' AS TYPE,
    ACCEPTER_ID AS ID,
    COUNT(DISTINCT REQUESTER_ID) AS NUM
FROM RequestAccepted
GROUP BY ID
)
SELECT
    ID AS id,
    SUM(NUM) AS num
FROM MATERIAL
GROUP BY ID
ORDER BY SUM(NUM) DESC
LIMIT 1

