WITH PREVIOUS AS (
    SELECT 
        ID,
        LAG(TEMPERATURE) OVER (ORDER BY RECORDDATE ASC) AS P_T,
        LAG(RECORDDATE) OVER (ORDER BY RECORDDATE ASC) AS P_D
    FROM WEATHER    
)
SELECT ID
FROM PREVIOUS AS PV
INNER JOIN WEATHER AS W
USING (ID)
WHERE 
    W.TEMPERATURE > PV.P_T
    AND DATEDIFF(W.RECORDDATE, PV.P_D) = 1
