# Write your MySQL query statement below
WITH PREVIOUS AS (
    SELECT 
        ID,
        LAG(TEMPERATURE) OVER (ORDER BY RECORDDATE ASC) AS P_T,
        LAG(RECORDDATE) OVER (ORDER BY RECORDDATE ASC) AS P_D
    FROM WEATHER    
)
SELECT ID
FROM PREVIOUS AS P
INNER JOIN WEATHER AS W
USING (ID)
WHERE 
    W.TEMPERATURE > P.P_T
    AND DATEDIFF(W.RECORDDATE, P.P_D) = 1
