WITH SALARY_TABLE AS (
    SELECT 
        NAME,
        SALARY,
        DEPARTMENTID,
        DENSE_RANK () OVER (PARTITION BY DEPARTMENTID ORDER BY SALARY DESC) AS SALARY_RANK
    FROM EMPLOYEE
)

SELECT 
    D.NAME AS Department,
    E.NAME AS Employee,
    E.SALARY AS Salary
FROM SALARY_TABLE AS E
INNER JOIN DEPARTMENT AS D
 ON E.DEPARTMENTID = D.ID
WHERE E.SALARY_RANK <= 3