WITH CANDIDATES AS (
    SELECT
        STUDENT_ID,
        SUBJECT,
        SCORE,
        exam_date,
        LAG(SCORE) OVER(PARTITION BY STUDENT_ID, SUBJECT ORDER BY EXAM_DATE) AS pre_score,
        LEAD(SCORE) OVER(PARTITION BY STUDENT_ID, SUBJECT ORDER BY EXAM_DATE) AS next_score
    FROM SCORES
)
SELECT 
    F.student_id,
    F.subject,
    F.SCORE AS first_score,
    L.SCORE AS latest_score
FROM CANDIDATES AS F
JOIN CANDIDATES AS L
ON F.STUDENT_ID = L.STUDENT_ID
AND F.SUBJECT = L.SUBJECT
AND F.pre_score is null
AND L.next_score is null
WHERE F.SCORE < L.SCORE