WITH CTE AS (
SELECT
    PLAYER_ID,
    DATEDIFF(EVENT_DATE, LEAD(EVENT_DATE) OVER(PARTITION BY PLAYER_ID ORDER BY EVENT_DATE)) AS DIFF,
    LAG(EVENT_DATE) OVER(PARTITION BY PLAYER_ID ORDER BY EVENT_DATE) AS PRE_LOGIN
FROM ACTIVITY
)
SELECT 
    ROUND(
        COUNT(*) / (SELECT COUNT(DISTINCT player_id) AS USER_COUNT FROM ACTIVITY),
        2
    ) AS fraction
FROM CTE
WHERE 
    PRE_LOGIN IS NULL
    AND DIFF = -1