CREATE FUNCTION getNthHighestSalary(N INT) RETURNS INT
BEGIN
  DECLARE SAL_RANK INT;
  SET SAL_RANK = N - 1;
  RETURN (
    SELECT DISTINCT SALARY 
    FROM EMPLOYEE 
    ORDER BY SALARY DESC
    LIMIT SAL_RANK, 1
  );
END